[project]
name = "fc25-visualizer"
version = "0.1.0"
description = "Visualizer for FC25 data"
readme = "readme.md"
requires-python = ">=3.10"
dependencies = [
    "jupyter>=1.1.1",
    "jupyterlab>=4.4.3",
    "pandas>=2.3.0",
    "scikit-learn>=1.7.0",
]
